bash:
  .bash_profile:
    source: "/bash/.bash_profile"
    dest: ".bash_profile"

python:
  .pylintrc:
    source: "/python/.pylintrc"
    dest: ".pylintrc"

atom:
  keymap.cson:
    source: "/atom/keymap.cson"
    dest: ".atom/keymap.cson"
  snippets.cson:
    source: "/atom/snippets.cson"
    dest: ".atom/snippets.cson"

vim:
  .vimrc:
    source: "/vim/.vimrc"
    dest: ".vimrc"

zsh:
  .zshrc:
    source: "/zsh/.zshrc"
    dest:  ".zshrc"
